DROP DATABASE IF EXISTS USER_MGT;
CREATE DATABASE USER_MGT;
USE USER_MGT;

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS(
	ID INT AUTO_INCREMENT,
	STREET_ADDRESS VARCHAR(255),
	CITY VARCHAR(100),
	POSTAL_CODE VARCHAR(10),
	COUNTRY VARCHAR(50),
	PRIMARY KEY (ID)
)ENGINE InnodB;

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
	ID INT AUTO_INCREMENT,
	FIRST_NAME VARCHAR(200),
	LAST_NAME VARCHAR(255),
	ADDRESS INT,
	JOINED_DATE DATE,
	PRIMARY KEY (ID),
 	FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ID)
) ENGINE InnodB;